### ISSUE TITLE
encodeConsentString() not optimal -- "Default Encoding" never set to 1 on ranges

### ISSUE THREAD

**Issue by UrbanAdManagement** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#31]
the function encodeConsentString only checks for rangesData with default Consent = false but not the opposite. depending on choices the oposite can result in a shorter consent string ...

**Comment by chrispaterson** [comment]
Valid issue, I'm going to set aside some time to look at this.

**Comment by chrispaterson** [comment]
So there are two parts to this I think:

1. encoding
in this case, there may be some optimizations to be gained by having the ability to flip the default consent.  However, we cannot have 'false positives' as @dmdabbs stated because of how vendors show up on the GVL.  So, for example, a consent string that has defaultConsent=true and range 1-maxVendorId cannot be valid if there are any gaps in the GVL where vendors will appear later because they will not be surfaced to the user.

But the case of defaultConsent=false and range 1-maxVendorId is valid because if a vendor isn't on the list, it doesn't have consent and when that vendor appears they have to capture consent.

Currently, the consent string tries both bitfield and range encoding and chooses the smaller of the two.

2. decoding
Currently, I see that this SDK does not decode the defaultConsent=true and range 1-maxVendorId correctly but I'm not sure if it's worth it include this as there is a thought of removing the defaultConsent value altogether in v2 and for it to be assumed to be false.
