### ISSUE TITLE
Make it compatible with IE9 & remove base-64 lib

### ISSUE THREAD

**Issue by Waschnick** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#5]
You would want to cover as many browsers as you can. Currently you can not really test the code with PhantomJS (I know, outdated, but the case is still valid) as for Array.from is not supported.

I would suggest for babel:

```
  "plugins": [
    "@59naga/babel-plugin-transform-array-from",
    "transform-es2015-arrow-functions",
    "transform-es2015-classes",
    "transform-es2015-destructuring",
    "transform-es2015-modules-commonjs",
    "transform-es2015-object-super",
    "transform-class-properties"
  ]
```

Only for Promises the user of the lib should have it's own Polyfill.

I would actually prefer to remove Array.from 

And one other thing: Skip on the base-64 library. You can easily do without it, it will decrease bundle size and dependencies.

**Comment by chrispaterson** [comment]
What would you recommend as a replacement for the base 64 encoding that needs to happen?

**Comment by jawadst** [comment]
For making it compatible with IE9, we should actually publish a fully built module instead of the source and make that as broad as possible. Maybe we should avoid using modern features like spread operators, arrow functions, etc. to keep the final build as lightweight as possible and not have to polyfill too much (ideally we shouldn't have to polyfill anything, just uglify).

For the base64 dependency, it is required for node.js but not for browsers (for browsers, we can use the standard atob/btoa functions). I think we can pass the base64 package to peer dependencies and do a runtime check.

**Comment by CanardSauvage** [comment]
You can transform (via webpack transforms) newer features, so it is still compatible with IE9. Only some features like Promises or Array.list/fill need Polyfills.

And for base64 it is as @jawadst seid.

**Comment by victuxbb** [comment]
Just for curiosity, why we need to support a 7 years old browser?

**Comment by CanardSauvage** [comment]
It's not only IE9, but other stuff to, like Android devices. As for IE9 as an example: Windows 7 is still widely used and does only have IE9 per default. It's a great benchmark and it's doable with acceptable effort.

And for Array.list/fill -> Not even IE11 supports it.

And for IAB Framework itself: You really want a wide browser coverage.

**Comment by victuxbb** [comment]
Being Windows 7 still widely used doesn't imply that the user didn't update the browser...
Taking a quick look about browsers usage, I don't know if the source is trusty but seems that IE9 is not widely used...
http://gs.statcounter.com/browser-market-share/all/europe

Also wikipedia show data from different sources:
https://en.wikipedia.org/wiki/Usage_share_of_web_browsers

Anyway I just want to say that sometimes we make our lifes more complicated because seems an acceptable effort ;)

**Comment by chrispaterson** [comment]
Does anyone have time to do these tasks that @jawadst has outlined and submit a pull request?

**Comment by victuxbb** [comment]
I can tackle the issue related to remove the dependency of base64 and do a PR

**Comment by victuxbb** [comment]
Oh! surprise, use window.atob and window.btoa functions are not supported in IE9
https://caniuse.com/#feat=atob-btoa
So we can remove the dependency only if we assume support for IE11 or greater

**Comment by alextremp** [comment]
Another option could be to use atob and btoa and set up a polyfill for unsupported browsers, p.ex.
[https://github.com/MaxArt2501/base64-js](https://github.com/MaxArt2501/base64-js)

**Comment by victuxbb** [comment]
Almost finished! Monday I will do PR, a lot of changes sorry...but there was a lot of coupling and no dependency injection ;)

**Comment by victuxbb** [comment]
@jawadst in reference about doing the build as lightweight as possible, has no sense in avoid using things like arrow functions, babel is **transpiling** the code, so if you don't use arrow functions you must write functions in a normal way, so finally the build will practically weight the same!
Take a look  in docs about transpiling arrow functions https://babeljs.io/docs/plugins/transform-es2015-arrow-functions/ and you will see that there is no weight increment ;)
If we speak about other features like classes is more complicated and probably in most of the cases the transpiled code will be bigger than original but we are speaking in a level of very small quantity, not relevant IMHO.

**Comment by jawadst** [comment]
@victuxbb I'd argue that it's hard to know what transpiling does ahead of time and what the impact on the final build size is. Arrow functions might not be expensive but I have no idea what the cost of every feature is.
Babelizing, as a general thing, is pretty expensive with polyfills and stuff.

I think that the build size is crucial here. We already distribute this lib at a pretty high scale in my company and every kb counts both from a performance and a cost perspective.

@alextremp Polyfilling would mean including the base-64 library that we already use and simply deciding which one to use at run time. It might be a little bit more efficient to use the browser one than the JS one but it wouldn't have any impact on the build size (which is fine).
In this case, the change should simply be that: use either window.atob functions or the base64 polyfill if needed but always include the polyfill.

**Comment by chrispaterson** [comment]
@jawadst @victuxbb The goal of this framework is adoption, so the choice should be made around ease of implementation.  That's the 'framework' I'd be making decisions around.  Removing dependencies helps adoption and reducing file size helps adoption.  The problem is identifying what items will make an impact on those things.  Let's review [Pull Request #13 ](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/pull/13) and see what we can optimize.

**Comment by nhagen** [comment]
Adding more specifics to the conversation about browser usage. https://caniuse.com/usage-table has IE9 + IE8 at 0.31% globally. I can't even find public statistics on IE9 usage in the EU specifically, and its likely even lower.
